Issue #11
marcominerva/TinyCMS pull request #22
Opened 2022-08-23 08:23 UTC by nanny07

Added support for database loaded stylesheets urls and raw content

2022-08-23 14:30 UTC, marcominerva requested changes
As described at https://github.com/marcominerva/TinyCMS/issues/11#issuecomment-1213162147, the `StyleSheetUrls` columns should be handled by a **Dapper Type Handler**. Moreover, having the calculated properties `GetAllStyleSheetContent` and `GetAllStyleSheetUrls` in the `ContentPage.cs` isn't a good solution. It is better to directly use the `StyleSheetUrls` and `StyleSheetContent` properties of `Site.cs` and `ContentPage.cs`, one after the other, so that, if necessary for future evolution, it will be more straightforward to handle them separately.

2022-08-24 07:10 UTC, nanny07 commented
Sorry, I've missed the line about **Dapper Type Handler**.
About the calculated properties (perhaps a method was a better choice) I was thinking of reducing the code's replication

2022-09-02 13:52 UTC, marcominerva requested changes

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms.DataAccessLayer/StringListTypeHandler.cs
> +﻿using System.Data;
Place the file in a folder names **TypeHandlers**.

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms.Shared/Models/ContentPage.cs
> +    public List<string> StyleSheetUrls { get; set; }
Declare the property as `string[]` and change the type handler name as `StringArrayTypeHandler`.

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            <link rel="stylesheet" href="@styleSheet" />
Add the version to the tag to prevent caching issues.

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            <link rel="stylesheet" href="@styleSheet" />
Add the version to the tag to prevent caching issues.

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            @Model.ContentPage.StyleSheetContent
This content should be sanitized.

2022-09-02 13:52 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            @Model.ContentPage.Site.StyleSheetContent
This content should be sanitized.

2022-09-02 15:10 UTC, nanny07 commented on src/TinyCms.BusinessLayer/Services/PageService.cs
> +                      , s.Id AS SiteId, s.Title AS SiteTitle, s.StyleSheetUrls AS SiteStyleSheetUrls, s.StyleSheetContent AS SiteStyleSheetContent
I used this notation because if you need, for example, to comment the row you haven't to delete the last comma in the previous line but... your project your rules 🤓

2022-09-05 06:28 UTC, nanny07 commented on src/TinyCms/Pages/Index.cshtml
> +            <link rel="stylesheet" href="@styleSheet" />
What number version should we put in there? A simple static string or something written, for example, in the appsettings?

2022-09-05 06:57 UTC, nanny07 commented on src/TinyCms/Pages/Index.cshtml
> +            @Model.ContentPage.StyleSheetContent
Is it ok to put tag `<raw>`  inside the tag `<style>`? Because if I put it outside of it the sanitization will clear all the content leave me an empty string

2022-09-05 12:40 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            <link rel="stylesheet" href="@styleSheet" />
You need to use this **TagHelper**: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.scripttaghelper.appendversion?view=aspnetcore-6.0

2022-09-05 12:41 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +            @Model.ContentPage.StyleSheetContent
It should be OK, of course make a test to verify that everything works as expected.

2022-09-07 08:28 UTC, marcominerva requested changes

2022-09-07 08:28 UTC, marcominerva commented on src/TinyCms.DataAccessLayer/TypeHandlers/StringArrayTypeHandler.cs
> +public class StringArrayTypeHandler : SqlMapper.TypeHandler<string[]>
This class should be `internal`.

2022-09-07 08:28 UTC, marcominerva commented on src/TinyCms.DataAccessLayer/TypeHandlers/StringArrayTypeHandler.cs
> +    private const string defaultSeparator = ";";
Move this constant before the `readonly` field and add a space between the two lines.

2022-09-07 08:28 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +}
Page specific stylesheets should come after Site stylesheets to allow the possibility to redefine styles.

2022-09-07 10:19 UTC, marcominerva requested changes

2022-09-07 10:19 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml
> +    }
You have correctly inverted Site and Page stylesheets order at lines 27-35, but you need to do the same here.

2022-09-07 10:36 UTC, marcominerva approved these changes

2022-09-07 10:37 UTC, merged