markdown
marcominerva/TinyCMS pull request #25
Opened 2022-10-11 11:03 UTC by andreatosato

For #6

2022-10-11 12:59 UTC, marcominerva requested changes
The Pull Request must be done in the `develop` branch.

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
Why do you have added this code?

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/Program.cs
> +builder.Services.AddMarkdown();
Why do you need this?

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/Program.cs
> +app.UseMarkdown();
Why do you need this?

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        html = Markdown.Parse(NormalizeWhiteSpaceText(html));
You aren't checking whether the content is actual HTML or Markdown: if the content is already HTML, you don't need to call the Markdown parser.

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +    private string NormalizeWhiteSpaceText(string text)
This method does not reference any local fields, so it can be marked as `static`.

2022-10-11 12:59 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +    private string[] GetLines(string s, int maxLines = 0)
This method is used only by `NormalizeWhiteSpaceText`, so it should be placed inside it.

2022-10-11 13:59 UTC, andreatosato commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
highlightjs is needed for formatting text markdown

2022-10-11 14:01 UTC, andreatosato commented on src/TinyCms/Program.cs
> +builder.Services.AddMarkdown();
For parse HTML to markdown text, sanitize and add html sections

2022-10-11 14:01 UTC, andreatosato commented on src/TinyCms/Program.cs
> +app.UseMarkdown();
For use extension markdown

2022-10-11 14:05 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
Doesn't the Markdown parser produce just plain HTML?

2022-10-11 14:06 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
Doesn't the Markdown parser produce just plain HTML?

2022-10-11 14:07 UTC, andreatosato commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
Yes, only sample HTML with specif tag that this library use for css and JS

2022-10-11 14:08 UTC, andreatosato commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
yes

2022-10-11 14:09 UTC, andreatosato commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +    private string NormalizeWhiteSpaceText(string text)
Why? I haven't error

2022-10-11 14:21 UTC, marcominerva requested changes

2022-10-11 14:21 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
So, why do you need this extra code for formatting? The site already includes Bootstrap, and code highlighting is beyond the scope of this issue.

2022-10-11 14:21 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        html = Markdown.Parse(NormalizeWhiteSpaceText(html));
You don't need to check markdown text, but check if the text is already HTML, and in this case avoid calling the Markdown parser.

2022-10-11 14:21 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        string[] GetLines(string s, int maxLines = 0)
As this method does not reference any local field, can be marked as `static`.

2022-10-11 14:21 UTC, marcominerva commented on src/TinyCms/Program.cs
> +app.UseMarkdown();
Are you sure? Check what this middleware does: https://github.com/RickStrahl/Westwind.AspNetCore.Markdown/blob/0976ec119952c1cc1638679d51ca6a2d4b9fffe2/Westwind.AspNetCore.Markdown/MarkdownPageProcessorMiddleware/MarkdownPageProcessorMiddleware.cs.

As you are manually parse markdown in **RawContentTagHelper.cs**, you don't need this at all.

2022-10-11 14:21 UTC, marcominerva commented on src/TinyCms/Program.cs
> +builder.Services.AddMarkdown();
Check what this extension method does: https://github.com/RickStrahl/Westwind.AspNetCore.Markdown/blob/b1a85cac9c0f7e60e5de3821cd78a265a3a7a992/Westwind.AspNetCore.Markdown/MarkdownPageProcessorMiddleware/MarkdownMiddlewareExtensions.cs#L22.

You don't need these services, because you are manually parsing the markdown. So, for example, in the **RawContentTagHelper.cs**, after parsing the markdown to HTML, you can easily call the already existing `HtmlExtensions.Sanitize` method.

2022-10-11 14:23 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
So, why do you need this extra code for formatting? The site already includes Bootstrap, and code highlighting is beyond the scope of this issue.

2022-10-11 14:26 UTC, andreatosato commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
If you want to see Markdown formatted, you need to style it.

2022-10-11 14:27 UTC, andreatosato commented on src/TinyCms/Program.cs
> +app.UseMarkdown();
I remove it

2022-10-11 14:27 UTC, andreatosato commented on src/TinyCms/Program.cs
> +builder.Services.AddMarkdown();
I remove it

2022-10-11 14:27 UTC, andreatosato commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +    private string NormalizeWhiteSpaceText(string text)
Check now

2022-10-11 14:30 UTC, andreatosato commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
We must highlightBlock any block <PRE> in code

2022-10-11 14:35 UTC, andreatosato commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        html = Markdown.Parse(NormalizeWhiteSpaceText(html));
do you wanto to ignore HTML script for markdown? Do you want only c#? Sure?

2022-10-11 14:47 UTC, marcominerva requested changes

2022-10-11 14:47 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +    </script>
As said, for this issue we don't want to handle code block, just plain HTML. For the moment we don't want to handle the `<pre>` tag. Of course, you can open a new issue to support code section ;)

2022-10-11 14:47 UTC, marcominerva commented on src/TinyCms/Pages/Shared/_Layout.cshtml
> +
As said, for this issue we don't want to handle code block, just plain HTML. For the moment we don't want to handle the `<pre>` tag. Of course, you can open a new issue to support code section ;)

2022-10-11 14:47 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        html = Markdown.Parse(NormalizeWhiteSpaceText(html));
I don't want any script at all :) I just want that the user can write a page in HTML or in markdown. For example, he can write something like this (I have added the code block only to maintain the original formatting):

```
* First item in an unordered list.
* Another item.
* Here we go again.
```

And the result on the page should be (again, the code block is only for original formatting):

```
<ol>
<li>First item in an unordered list.</li>
<li>Another item.</li>
<li>Another item.</li>
</ol>
```

2022-10-12 08:24 UTC, marcominerva requested changes

2022-10-12 08:24 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
>          var html = childContent.GetContent(NullHtmlEncoder.Default);
As now the content might not be HTML, probably it is better to rename the variabile as `content`.

2022-10-12 08:24 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        html = Markdown.ToHtml(html);
You still do not check if the content is actually markdown. This is important to prevent unnecessary parsing. We can use for example a regular expression: https://uibakery.io/regex-library/html-regex-csharp. At this moment, we aren't interested in supporting mixed scenarios (content with both HTML and markdown).

2022-10-12 08:24 UTC, marcominerva commented on src/TinyCms/TinyCms.csproj
> +    <PackageReference Include="HtmlSanitizer" Version="7.1.542" />    <PackageReference Include="Markdig" Version="0.30.4" />
Incorrect formatting of the file

2022-10-12 12:32 UTC, marcominerva requested changes

2022-10-12 12:32 UTC, marcominerva commented on src/TinyCms/TagHelpers/RawContentTagHelper.cs
> +        var isHtml = Regex.Match(content, "<(?:\"[^\"]*\"['\"]*|'[^']*'['\"]*|[^'\">])+>");
As you're always using the same expression, it is better to define a static `Regex` field at class level with the `RegexOptions.Compiled` option.

2022-10-12 14:48 UTC, merged