dev/N1K0232/issue33
marcominerva/TinyCMS pull request #56
Opened 2023-10-16 18:57 UTC by N1K0232

Solved issue #33
Actually this is the solution I've found to solve the description provided in the issue.

Hope the solution matches the final idea and hope I've been helpful :)

2023-10-17 07:31 UTC, marcominerva requested changes

2023-10-17 07:31 UTC, marcominerva commented on src/TinyCms.BusinessLayer/Services/PageService.cs
> +                        s.Id AS SiteId, s.Title AS SiteTitle, s.IsPublished AS IsSitePublished, s.StyleSheetUrls AS SiteStyleSheetUrls, s.StyleSheetContent AS SiteStyleSheetContent
The requirement is to give a 404 error if the site isn't published, so it is not necessary to return this column value and then check it in the `Index.cshtml.cs` page. You can simply add this condition in the WHERE clause so that the content page at all isn't returned.

2023-10-17 07:31 UTC, marcominerva commented on src/TinyCms.DataAccessLayer/SqlContext.cs
> +            ["IsSitePublished"] = "IsPublished"
Based on the previous comment, this mapping isn't necessary.

2023-10-17 07:31 UTC, marcominerva commented on src/TinyCms.Shared/Models/Site.cs
> +    public bool IsPublished { get; set; }
Based on previous comments, this property isn't necessary.

2023-10-17 07:31 UTC, marcominerva commented on src/TinyCms/Pages/Index.cshtml.cs
> +        if (ContentPage is null || !ContentPage.Site.IsPublished)
Based on previous comments, this change isn't necessary.

2023-10-17 12:04 UTC, N1K0232 commented on src/TinyCms.BusinessLayer/Services/PageService.cs
> +                        s.Id AS SiteId, s.Title AS SiteTitle, s.IsPublished AS IsSitePublished, s.StyleSheetUrls AS SiteStyleSheetUrls, s.StyleSheetContent AS SiteStyleSheetContent
Thank you for the review and thank you for the correction.
I also want to apologize. I didn't think to use the WHERE clause

2023-10-17 16:10 UTC, N1K0232 commented
Done :)

2023-10-18 07:41 UTC, marcominerva approved these changes

2023-10-18 07:44 UTC, merged